// Firebase fetching reducers
export const FETCH_UID_FIREBASE_START = 'FETCH_UID_FIREBASE_START';
export const FETCH_UID_FIREBASE_DONE = 'FETCH_UID_FIREBASE_DONE';
export const FETCH_CLASSROOMS_FIREBASE_START = 'FETCH_CLASSROOMS_FIREBASE_START';
export const FETCH_CLASSROOMS_FIREBASE_DONE = 'FETCH_CLASSROOMS_FIREBASE_DONE';
export const SAVE_BOOKING_FIREBASE_START = 'SAVE_BOOKING_FIREBASE_START';
export const SAVE_BOOKING_FIREBASE_DONE = 'SAVE_BOOKING_FIREBASE_DONE';

// Decision reducers
export const CHOOSE_SEAT = 'CHOOSE_SEAT';

// Cancel/regret reducers
export const CANCEL_BOOKING_START = 'CANCEL_BOOKING_START';
export const CANCEL_BOOKING_DONE = 'CANCEL_BOOKING_DONE';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const REGRET_CHOSEN_SEAT = 'REGRET_CHOSEN_SEAT';

// Modal reducers
export const SHOW_CANCEL_BOOKING_MODAL = 'SHOW_CANCEL_BOOKING_MODAL';
export const HIDE_CANCEL_BOOKING_MODAL = 'HIDE_CANCEL_BOOKING_MODAL';
export const SHOW_CANCEL_BOOKING_DONE_MODAL = 'SHOW_CANCEL_BOOKING_DONE_MODAL';
export const HIDE_CANCEL_BOOKING_DONE_MODAL = 'HIDE_CANCEL_BOOKING_DONE_MODAL';
export const HIDE_BOOKING_CONFIRMATION_MODAL = 'HIDE_BOOKING_CONFIRMATION_MODAL';